import http.server
import ssl

# Set the server address and port (using 8443 for HTTPS)
server_address = ('localhost', 8443)
handler = http.server.SimpleHTTPRequestHandler

httpd = http.server.HTTPServer(server_address, handler)

# Wrap the socket with SSL using the certificates generated by mkcert
httpd.socket = ssl.wrap_socket(
    httpd.socket,
    server_side=True,
    certfile="localhost.pem",        # Your mkcert certificate for localhost
    keyfile="localhost-key.pem",     # The corresponding private key
    ssl_version=ssl.PROTOCOL_TLS
)

print("Serving HTTPS on https://localhost:8443...")
httpd.serve_forever()

